"""add_extraction_meta_and_medical_knowledge

Revision ID: a676b104e188
Revises: 
Create Date: 2026-04-30 01:25:28.584405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a676b104e188'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extractions', sa.Column('source', sa.String(length=30), nullable=True))
    op.add_column('extractions', sa.Column('ocr_method', sa.String(length=40), nullable=True))
    op.add_column('extractions', sa.Column('ocr_confidence', sa.Float(), nullable=True))
    op.add_column('extractions', sa.Column('phi_detected', sa.Boolean(), nullable=True))
    op.add_column('extractions', sa.Column('document_type', sa.String(length=30), nullable=True))
    op.alter_column('extractions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_extractions_created_at'), 'extractions', ['created_at'], unique=False)
    op.create_index(op.f('ix_extractions_status'), 'extractions', ['status'], unique=False)
    op.create_index('ix_extractions_status_created', 'extractions', ['status', 'created_at'], unique=False)
    op.add_column('medical_knowledge', sa.Column('source_extractions', sa.Text(), nullable=True))
    op.create_index('ix_knowledge_category_confidence', 'medical_knowledge', ['category', 'confidence'], unique=False)
    op.create_index(op.f('ix_medical_knowledge_category'), 'medical_knowledge', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_knowledge_category'), table_name='medical_knowledge')
    op.drop_index('ix_knowledge_category_confidence', table_name='medical_knowledge')
    op.drop_column('medical_knowledge', 'source_extractions')
    op.drop_index('ix_extractions_status_created', table_name='extractions')
    op.drop_index(op.f('ix_extractions_status'), table_name='extractions')
    op.drop_index(op.f('ix_extractions_created_at'), table_name='extractions')
    op.alter_column('extractions', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('extractions', 'document_type')
    op.drop_column('extractions', 'phi_detected')
    op.drop_column('extractions', 'ocr_confidence')
    op.drop_column('extractions', 'ocr_method')
    op.drop_column('extractions', 'source')
    # ### end Alembic commands ###
