export const entityColors = {
    DRUG: "bg-rose-50 text-rose-700",
    DOSAGE: "bg-emerald-50 text-emerald-700",
    DURATION: "bg-amber-50 text-amber-700",
    FORM: "bg-violet-50 text-violet-700",
    FREQUENCY: "bg-sky-50 text-sky-700",
    ROUTE: "bg-orange-50 text-orange-700",
    STRENGTH: "bg-teal-50 text-teal-700",
    LATIN_INSTRUCTION: "bg-slate-100 text-slate-700",
    FREQUENCY_LATIN: "bg-blue-50 text-blue-700",
    DISEASE: "bg-red-50 text-red-700",
    SYMPTOM: "bg-yellow-50 text-yellow-700",
    ANATOMY: "bg-pink-50 text-pink-700",
    PROCEDURE: "bg-indigo-50 text-indigo-700",
    LAB: "bg-cyan-50 text-cyan-700",
};

export const entityBorderColors = {
    DRUG: "border border-rose-200",
    DOSAGE: "border border-emerald-200",
    DURATION: "border border-amber-200",
    FORM: "border border-violet-200",
    FREQUENCY: "border border-sky-200",
    ROUTE: "border border-orange-200",
    STRENGTH: "border border-teal-200",
    LATIN_INSTRUCTION: "border border-slate-200",
    FREQUENCY_LATIN: "border border-blue-200",
    DISEASE: "border border-red-200",
    SYMPTOM: "border border-yellow-200",
    ANATOMY: "border border-pink-200",
    PROCEDURE: "border border-indigo-200",
    LAB: "border border-cyan-200",
};